services:
  graphviz:
    build:
      context: ./dockerfiles
      dockerfile: graphviz.Dockerfile
    volumes:
      - ../cache:/data
  graphviz-server:
    build:
      context: ./dockerfiles/graphviz-server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  apache:
    image: httpd:latest
    volumes:
      - ../docs:/usr/local/apache2/htdocs/
    ports:
      - 80:80
