services:
  graphviz:
    build:
      context: ./dockerfiles
      dockerfile: graphviz.Dockerfile
    volumes:
      - ../cache:/data
  apache:
    image: httpd:latest
    volumes:
      - ../view:/usr/local/apache2/htdocs/
    ports:
      - 80:80
